### ISSUE TITLE
deploy with --prefix and  --environment has some display issue

### ISSUE THREAD

**Issue by htchen829** [aws-samples/drs-tools#6]
In the readme, it says "The environment name to append to the end of each stack name, eg environment 'dev' results in stack name 'drs-configuration-synchronizer-dev' "
But actually, when deploy with --environment, the cloudformation stacks, will append env directly without "-", eg environment 'dev' results in stack name 'drs-configuration-synchronizerdev' not 'drs-configuration-synchronizer-dev'

In addition, even I specified --prefix, some stacks will not show prefix:
drs-plan-automation-tables
drs-plan-automation-codepipeline
drs-plan-automation-sns-notifications
drs-plan-automation-iam-cloudformationrole

And they also don't have correct environments appended in stack names.
<img width="619" alt="Screen Shot 2022-12-25 at 11 26 11 PM" src="https://user-images.githubusercontent.com/58508308/209473953-15a98f0f-4a25-496a-892c-ba698d3c3db9.png">

**Comment by knizami** [comment]
Hello, thank you for submitting this issue.  You are correct, the stacks deployed by the pipeline didn't have the prefix and there was a missing dash in the suffix.  This should be fixed today.
